### ISSUE TITLE
Have your models been successfully trained?

### ISSUE THREAD

**Issue by SuperheroZLP** [sunghoonhong/AirsimDRL#16]
Hello, have your models been successfully trained?   In the “Easy” environment, I used the models saved in your project to conduct many rounds of testing， but the success rate was very low, and I didn't even succeed.
And, how long does it take to train a successful model?
Looking forward to your reply, thank you.

**Comment by kongbinGH** [comment]
D:\anaconda3\envs\tensorflow_gpu\python.exe D:\AirsimDRL-master\td3_per.py 
2024-11-01 20:51:22.386716: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-01 20:51:22.760542: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13575 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060 Ti, pci bus id: 0000:01:00.0, compute capability: 8.9
2024-11-01 20:51:22.768051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13575 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060 Ti, pci bus id: 0000:01:00.0, compute capability: 8.9
WARNING:tensorflow:Layer gru will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer gru_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
Connected!
Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)

Last episode: 2141
Best Y: 57.59
Traceback (most recent call last):
  File "D:\AirsimDRL-master\td3_per.py", line 578, in <module>
    observe = env.reset()
  File "D:\AirsimDRL-master\airsim_env.py", line 55, in reset
    responses = self.client.simGetImages(
  File "D:\anaconda3\envs\tensorflow_gpu\lib\site-packages\airsim\client.py", line 266, in simGetImages
    responses_raw = self.client.call('simGetImages', requests, vehicle_name, external)
  File "D:\anaconda3\envs\tensorflow_gpu\lib\site-packages\msgpackrpc\session.py", line 41, in call
    return self.send_request(method, args).get()
  File "D:\anaconda3\envs\tensorflow_gpu\lib\site-packages\msgpackrpc\future.py", line 45, in get
    raise error.RPCError(self._error)
msgpackrpc.error.RPCError: rpclib: client error C0002: Function 'simGetImages' was called with an invalid number of arguments. Expected: 3, got: 2

Process finished with exit code 1
——————————————————————————————————————————————————————————

Hello, I have encountered the above problems. Could you please share your AirSim version, TensorFlow version, and Keras version? It would be better if you can provide requirements.txt. I look forward to your reply, thank you.

**Comment by kongbinGH** [comment]
> Hello, have your models been successfully trained? In the “Easy” environment, I used the models saved in your project to conduct many rounds of testing， but the success rate was very low, and I didn't even succeed. And, how long does it take to train a successful model? Looking forward to your reply, thank you.

D:\anaconda3\envs\tensorflow_gpu\python.exe D:\AirsimDRL-master\td3_per.py
2024-11-01 20:51:22.386716: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-01 20:51:22.760542: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13575 MB memory: -> device: 0, name: NVIDIA GeForce RTX 4060 Ti, pci bus id: 0000:01:00.0, compute capability: 8.9
2024-11-01 20:51:22.768051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13575 MB memory: -> device: 0, name: NVIDIA GeForce RTX 4060 Ti, pci bus id: 0000:01:00.0, compute capability: 8.9
WARNING:tensorflow:Layer gru will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer gru_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
Connected!
Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)

Last episode: 2141
Best Y: 57.59
Traceback (most recent call last):
File "D:\AirsimDRL-master\td3_per.py", line 578, in
observe = env.reset()
File "D:\AirsimDRL-master\airsim_env.py", line 55, in reset
responses = self.client.simGetImages(
File "D:\anaconda3\envs\tensorflow_gpu\lib\site-packages\airsim\client.py", line 266, in simGetImages
responses_raw = self.client.call('simGetImages', requests, vehicle_name, external)
File "D:\anaconda3\envs\tensorflow_gpu\lib\site-packages\msgpackrpc\session.py", line 41, in call
return self.send_request(method, args).get()
File "D:\anaconda3\envs\tensorflow_gpu\lib\site-packages\msgpackrpc\future.py", line 45, in get
raise error.RPCError(self._error)
msgpackrpc.error.RPCError: rpclib: client error C0002: Function 'simGetImages' was called with an invalid number of arguments. Expected: 3, got: 2

Process finished with exit code 1
——————————————————————————————————————————————————————————

Hello, I have encountered the above problems. Could you please share your AirSim version, TensorFlow version, and Keras version? It would be better if you can provide requirements.txt. I look forward to your reply, thank you.
